library(readr)
Student <- read_csv(
  "data/Student.csv",
  col_types = cols(
    class_group = col_factor(levels = c("A","B","C")),
    gender = col_factor(levels = c("0","1")),
    regret_choosing_bi = col_factor(levels = c("0","1")),
    drop_bi_now = col_factor(levels = c("0","1")),
    motivator = col_factor(levels = c("0","1")),
    read_content_before_lecture = col_factor(levels = c("0","1","2","3","4","5")),
    anticipate_test_questions = col_factor(levels = c("0","1","2","3","4","5")),
    answer_rhetorical_questions = col_factor(levels = c("0","1","2","3","4","5")),
    copy_new_terms_in_reading_notebook = col_factor(levels = c("0","1","2","3","4","5")),
    take_quizzes_and_use_results = col_factor(levels = c("0","1","2","3","4","5")),
    read_content_before_lecture = col_factor(levels = c("0","1","2","3","4","5")),
    reorganise_course_outline = col_factor(levels = c("0","1","2","3","4","5")),
    write_down_important_points = col_factor(levels = c("0","1","2","3","4","5")),
    space_out_revision = col_factor(levels = c("0","1","2","3","4","5")),
    studying_in_study_group = col_factor(levels = c("0","1","2","3","4","5")),
    schedule_appointments = col_factor(levels = c("0","1","2","3","4","5")),
    goal_oriented = col_factor(levels = c("0","1")),
    spaced_repetition = col_factor(levels = c("0","1","2","3","4","5")),
    testing_and_active_recall = col_factor(levels = c("0","1","2","3","4","5")),
    interleaving = col_factor(levels = c("0","1","2","3","4","5")),
    categorizing = col_factor(levels = c("0","1","2","3","4","5")),
    retrospective_timetable = col_factor(levels = c("0","1","2","3","4","5")),
    cornell_notes = col_factor(levels = c("0","1","2","3","4","5")),
    sq3r = col_factor(levels = c("0","1","2","3","4","5")),
    commute = col_factor(levels = c("0","1","2","3","4","5")),
    study_time = col_factor(levels = c("0","1","2","3","4","5")),
    repeats_since_Y1 = col_integer(),
    paid_tuition = col_factor(levels = c("0","1")),
    free_tuition = col_factor(levels = c("0","1")),
    extra_curricular = col_factor(levels = c("0","1")),
    sports_extra_curricular = col_factor(levels = c("0","1")),
    exercise_per_week = col_integer(),
    meditate = col_integer(),
    pray = col_integer(),
    internet = col_factor(levels = c("0","1")),
    laptop = col_factor(levels = c("0","1")),
    family_relationships = col_factor(levels = c("0","1","2","3","4","5")),
    friendships = col_factor(levels = c("0","1","2","3","4","5")),
    romantic_relationships = col_factor(levels = c("0","1","2","3","4","5")),
    spiritual_wellnes = col_factor(levels = c("0","1","2","3","4","5")),
    financial_wellness = col_factor(levels = c("0","1","2","3","4","5")),
    health = col_factor(levels = c("0","1","2","3","4","5")),
    day_out = col_integer(),
    night_out = col_integer(),
    alcohol_or_narcotics = col_factor(levels = c("0","1")),
    mentor = col_factor(levels = c("0","1")),
    mentor_meetings = col_factor(levels = c("0","1")),
  ))
View(Student)
# Imported the dataset


